app:
  name: "bytezero-go"
  version: "v1.0.0"
  server:
    up: true
    ip: 61.164.248.149
    port: 7788
    margic: false
  tls:
    up: true
    ip: 61.164.248.149
    port: 7789
    cacert: "./scripts/certs/server/server.crt"
    cakey: "./scripts/certs/server/server.key"
  web:
    http:
      up: true
      host: 61.164.248.149:7790
      heart: 3000
    https:
      up: true
      host: 61.164.248.149:7791
      cacert: "./scripts/certs/server/server.crt"
      cakey: "./scripts/certs/server/server.key"
    static:
      up: true
      uploadPath: "./bin/caches/files/upload/"
      logPath: "./bin/log/"
      memory: 10240000
  maxBufferLen: 10485760
  rwBufferLen: 10485760
  appid: bytezero-appid
  appkey: secret
  accessIpsAllow: "./scripts/.accessIps.allow"
  accessIpsDeny: "./scripts/.accessIps.idc6.deny"
  credential:
    expiredMs: 3600000
    urls:
      - tcp://61.164.248.149:7788
      - tls://61.164.248.149:7789

