app:
  name: "bytezero-go"
  version: "v1.0.0"
  server:
    up: true
    ip: 192.168.90.116
    port: 7788
    margic: true
  tls:
    up: true
    ip: 192.168.90.116
    port: 7789
    cacert: "./scripts/certs/server/server.crt"
    cakey: "./scripts/certs/server/server.key"
  web:
    http:
      up: true
      host: 192.168.90.116:7790
      heart: 3000
    https:
      up: true
      host: 192.168.90.116:7791
      cacert: "./scripts/certs/server/server.crt"
      cakey: "./scripts/certs/server/server.key"
    static:
      up: true
      uploadPath: "./bin/caches/files/upload/"
      logPath: "./bin/log/"
      memory: 10240000
  maxBufferLen: 10485760
  rwBufferLen: 10485760
  appid: bytezero-appid
  appkey: secret
  credential:
    expiredMs: 60000
    urls:
      - tcp://192.168.90.116:7788
      - tls://192.168.90.116:7789

