app:
  name: "bytezero-go"
  version: "v1.0.0"
  server:
    up: true
    ip: 0.0.0.0
    port: 17788
    margic: false
  tls:
    up: true
    ip: 0.0.0.0
    port: 17789
    cacert: "./scripts/certs/server/server.crt"
    cakey: "./scripts/certs/server/server.key"
  web:
    http:
      up: true
      #host: 183.6.87.13:17790
      host: 0.0.0.0:17790
      heart: 3000
    https:
      up: true
      host: 0.0.0.0:17791
      cacert: "./scripts/certs/server/server.crt"
      cakey: "./scripts/certs/server/server.key"
    static:
      up: true
      uploadPath: "./bin/caches/files/upload/"
      logPath: "./bin/log/"
      memory: 10240000
  maxBufferLen: 10485760
  rwBufferLen: 10485760
  appid: bytezero-appid
  appkey: secret
  logPath: "./bin/log/bytezero_main"
  accessIpsAllow: "./scripts/.accessIps.allow"
  accessIpsDeny: "./scripts/.accessIps.deny"
  credential:
    expiredMs: 3600000
    urls:
      - tcp://183.6.87.13:17788
      - tls://183.6.87.13:17789

